initialDir          = /sphenix/user/tmengel/dijet-ana-auau/condor
Universe            = vanilla
Executable          = $(initialDir)/sim2.sh
PeriodicHold        = (NumJobStarts>=1 && JobStatus == 1)
request_memory      = 6GB
Priority            = 20
batch_name          = sim2
versionTag          = 08_14_2026_v001
condorDir           = $(initialDir)/logs/08_14_2026_v001
Output              = $(condorDir)/pass1-$(id).out
Error               = $(condorDir)/pass1-$(id).err
Log                 = /tmp/condorjob-tmengel.log
Arguments           = "$(id) $(versionTag)"
Queue id from $(initialDir)/held.list
